'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SlimOS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Application_Icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Application_Icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;settings&gt;
        '''	&lt;OperatingSystems&gt;
        '''		&lt;Default&gt;SlimOS&lt;/Default&gt;
        '''		&lt;Timeout&gt;0&lt;/Timeout&gt;
        '''	&lt;/OperatingSystems&gt;
        '''	
        '''	&lt;SlimOS&gt;
        '''		&lt;DisplayName&gt;SlimOS&lt;/DisplayName&gt;
        '''		&lt;BootOptions&gt;None&lt;/BootOptions&gt;
        '''		&lt;BootPath&gt;.&lt;/BootPath&gt;
        '''	&lt;/SlimOS&gt;
        '''&lt;/settings&gt;.
        '''</summary>
        Friend ReadOnly Property boot() As String
            Get
                Return ResourceManager.GetString("boot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;settings&gt;
        '''	&lt;setting&gt;
        '''	&lt;DefaultUser&gt;Administrator&lt;/DefaultUser&gt;
        '''	&lt;GuestAccountEnabled&gt;False&lt;/GuestAccountEnabled&gt;
        '''	&lt;AutoDimDisplay&gt;5&lt;/AutoDimDisplay&gt;
        '''	&lt;AutoOffDisplay&gt;10&lt;/AutoOffDisplay&gt;
        '''	&lt;AutoStandby&gt;15&lt;/AutoStandby&gt;
        '''	&lt;AutoTurnOff&gt;-1&lt;/AutoTurnOff&gt;
        '''	&lt;ScreensaverTimeout&gt;3&lt;/ScreensaverTimeout&gt;
        '''	&lt;RequirePasswordOnResume&gt;False&lt;/RequirePasswordOnResume&gt;
        '''	&lt;/setting&gt;
        '''&lt;/settings&gt;.
        '''</summary>
        Friend ReadOnly Property config() As String
            Get
                Return ResourceManager.GetString("config", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property keyboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("keyboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shift_alt_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shift_alt_l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SlimOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SlimOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property StartIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;settings&gt;
        '''	&lt;setting&gt;
        '''	&lt;ShowLogonExtendedOptions&gt;False&lt;/ShowLogonExtendedOptions&gt;
        '''	&lt;ErrorLevel&gt;1&lt;/ErrorLevel&gt;
        '''	&lt;/setting&gt;
        '''&lt;/settings&gt;.
        '''</summary>
        Friend ReadOnly Property system() As String
            Get
                Return ResourceManager.GetString("system", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;settings&gt;
        '''  &lt;setting&gt;
        '''    &lt;user&gt;Dakota&lt;/user&gt;
        '''    &lt;password&gt;reno97&lt;/password&gt;
        '''    &lt;user&gt;Guest&lt;/user&gt;
        '''    &lt;password&gt;&lt;/password&gt;
        '''	&lt;user&gt;Administrator&lt;/user&gt;
        '''	&lt;password&gt;admin&lt;/password&gt;
        '''  &lt;/setting&gt;
        '''&lt;/settings&gt;.
        '''</summary>
        Friend ReadOnly Property users() As String
            Get
                Return ResourceManager.GetString("users", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
